<main class="form-signin w-100 m-auto">
  <form action="index.php?route=login" method="POST">
    <h1 class="h3 mb-3 fw-normal">Login</h1>

    <div class="form-floating">
      <input type="email" class="form-control" name="login-email" id="login-email" placeholder="name@example.com">
      <label for="login-email">Email address</label>
    </div>
    <div class="form-floating">
      <input ttype="password" name="login-password" id="login-password" class="form-control" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="form-check text-start my-3">
        <a href="index.php?route=register">Register</a>
    </div>
    <button class="btn btn-primary w-100 py-2" type="submit" name="submit-login" id="submit-login" value="Se connecter">Sign in</button>
    <p class="mt-5 mb-3 text-body-secondary" >© 2017–2023</p>
  </form>
</main>
