<h1>Créer un compte</h1>
<form action="index.php?route=register" method="POST">
    <fieldset>
        <label for="register-first-name">Prénom</label>
        <input type="text" name="register-first-name" id="register-first-name"/>
    </fieldset>
    <fieldset>
        <label for="register-last-name">Nom</label>
        <input type="text" name="register-last-name" id="register-last-name"/>
    </fieldset>
    <fieldset>
        <legend>Adresse</legend>
        <label for="register-adress-number">N°</label>
        <input type="text" name="register-adress-number" id="register-adress-number"/>
        <label for="register-adress-street">Voie</label>
        <input type="text" name="register-adress-street" id="register-adress-street"/>
        <label for="register-adress-postal-code">Code postal</label>
        <input type="text" name="register-adress-postal-code" id="register-adress-postal-code"/>
        <label for="register-adress-city">Ville</label>
        <input type="text" name="register-adress-city" id="register-adress-city"/>
    </fieldset>
    <fieldset>
        <label for="register-email">Email</label>
        <input type="email" name="register-email" id="register-email"/>
    </fieldset>
    <fieldset>
        <label for="register-password">Mot de passe</label>
        <input type="password" name="register-password" id="register-password"/>
    </fieldset>
    <fieldset>
        <label for="register-confirm-password">Confirmer le mot de passe</label>
        <input type="password" name="register-confirm-password" id="register-confirm-password"/>
    </fieldset>
    <input type="submit" name="submit-new-user" value="Créer un compte"/>
</form>