
<table>
    <thead>
        <tr>
            <th>Nom du produit</th>
            <th>Prix</th>
        </tr>
    </thead>
    <tbody>
    <?php
    $total_price=0;
    foreach( $_SESSION['cart'] as $product)
    {
        $total_price += $product->getPrice();
        ?>
            <tr>
                <td><?=$product->getName();?> </td>
                <td><?=$product->getPrice()." €";?></td>
            </tr>
        <?php
    }
    ?>
    <tfoot>
    <tr>
        <td>Total</td>
        <td><?=$total_price." €";?></td>
    </tr>
    </tfoot>
    </tbody>
</table>
<form method="POST" action="index.php?route=cart">
    <input class="btn btn-sm btn-outline-secondary" type="submit" name="add-order" id="add-order" value="Valider le panier">
</form>

